---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    facing: worker
    service: fktwttr
    type: stupid-twitter-bot
  name: fktwttr-stpdbot
spec:
  replicas: 1
  selector:
    name: fktwttr-stpdbot
  template:
    metadata:
      labels:
        name: fktwttr-stpdbot
    spec:
      containers:
        -
          image: quay.io/purplebooth/fucking-twitter-bot:latest
          imagePullPolicy: Always
          name: fktwttr-stpdbot
          env:
            - name: SECRETS_PATH
              value: /secrets/fucking-twitter-bot.cfg
            - name: WORDLIST_KEY
              value: fucking
            - name: REDIS_ENV_TUTUM_SERVICE_HOSTNAME
              value: fktwttr-redis
          volumeMounts:
            -
              mountPath: /secrets
              name: twitter-secrets
      restartPolicy: Always
      volumes:
        -
          name: twitter-secrets
          secret:
            secretName: twitter-secrets
