---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    facing: worker
    service: fktwttr
    type: redis
  name: fktwttr-redis-v0
spec:
  replicas: 1
  selector:
    service: fktwttr
    type: redis
    version: v0
  template:
    metadata:
      labels:
        service: fktwttr
        type: redis
        version: v0
    spec:
      containers:
        -
          image: redis
          imagePullPolicy: Always
          name: fktwttr-redis
          cmd: ["redis"]
          args: ["redis-server","--appendonly","yes"]
          ports:
            -
              containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            -
              mountPath: /data
              name: fktwttr-redis-pv
          livenessProbe:
                exec:
                  command:
                  - redis-cli
                  - INFO
                initialDelaySeconds: 15
                timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        -
          persistentVolumeClaim:
              claimName: fktwttr-redis-pvc
          name: fktwttr-redis-pv
